### PR TITLE
PXY-860 Add metadata to Plugins

### PR DESCRIPTION
**Pull request by framiere**
The objective is to be able to give more context for each plugin.
Any UI wanted to surface these plugins will need a way to get some metadata about them.

### CODE REVIEW

**Review by fteychene — COMMENTED** [review]
Could you add a description of the change ?

Also a question regarding format and loading with multiple plugins

**Comment by framiere** [comment]
@fteychene good?

**Review by thomaskwscott — APPROVED** [review]
LGTM

**Comment by framiere** [comment]
1. There's no more examples, example should live in doc (Francois is right)
2. yes when we'll release 0.5.0 (we are currently in 0.5.0-SNAPSHOT)

**Comment by thomaskwscott** [comment]
> 1. There's no more examples, example should live in doc (Francois is right)
> 2. yes when we'll release 0.5.0 (we are currently in 0.5.0-SNAPSHOT)

If the purpose of this is for the UI then it must contain an example JSON, otherwise it's useless imo. Can we do another PR that covers this?

**Pull request merged**
